name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
            cd Frontend
            npm ci

      - name: Run tests
        run: |
            cd Frontend        
            npm run test
            
      - name: Build
        run: |
            cd Frontend
            npm run build

